version: '3.8'

services:
  backend:
    image: wtb-backend:deploy
    container_name: wtb-backend
    environment:
      DB_DSN: "host=host.docker.internal user=admin password=wtb123456 port=5432 sslmode=disable TimeZone=Asia/Shanghai"
      IMAGE_PATH: "/app/images"
      WX_APPID: "wx1e4315d1974c72f6"
      WX_APPSECRET: "c4e88e19973ab1c7ac21ad5b27f4f742"
      WX_ENV_VERSION: "trial"
    ports:
      - "18080:8080"
    volumes:
      - ../../images:/app/images
      - ../../uploads:/app/uploads
    networks:
      - wtb-network
    restart: unless-stopped

networks:
  wtb-network:
