package handler
import ("strconv"; "github.com/gin-gonic/gin"; "github.com/wtb-ordering/pkg/response"; "github.com/wtb-ordering/services/activity/model"; "github.com/wtb-ordering/services/activity/service")
type ActivityHandler struct{ svc *service.ActivityService }
func NewActivityHandler(svc *service.ActivityService) *ActivityHandler { return &ActivityHandler{svc: svc} }
func (h *ActivityHandler) ListAnnouncements(c *gin.Context) { list, err := h.svc.ListAnnouncements(); if err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, list) }
func (h *ActivityHandler) ListActivities(c *gin.Context) { list, err := h.svc.ListActivities(); if err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, list) }
func (h *ActivityHandler) Register(c *gin.Context) { id, _ := strconv.ParseUint(c.Param("id"), 10, 64); var req struct{ Name string `json:"name"`; Phone string `json:"phone"`; Remark string `json:"remark"` }; if err := c.ShouldBindJSON(&req); err != nil { response.Error(c, 40001, "参数错误"); return }; uid, _ := strconv.ParseUint(c.GetString("user_id"), 10, 64); reg, err := h.svc.Register(uint(uid), uint(id), req.Name, req.Phone, req.Remark); if err != nil { if err.Error() == "活动名额已满" { response.Error(c, 40006, err.Error()); return }; if err.Error() == "已报名" { response.Error(c, 40008, err.Error()); return }; response.Error(c, 50001, err.Error()); return }; response.Success(c, reg) }
func (h *ActivityHandler) MyRegistrations(c *gin.Context) { uid, _ := strconv.ParseUint(c.GetString("user_id"), 10, 64); list, err := h.svc.MyRegistrations(uint(uid)); if err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, list) }
func (h *ActivityHandler) CancelRegistration(c *gin.Context) { id, _ := strconv.ParseUint(c.Param("id"), 10, 64); uid, _ := strconv.ParseUint(c.GetString("user_id"), 10, 64); if err := h.svc.CancelRegistration(uint(uid), uint(id)); err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, gin.H{"activity_id": id}) }
func (h *ActivityHandler) CreateAnnouncement(c *gin.Context) { var a model.Announcement; if err := c.ShouldBindJSON(&a); err != nil { response.Error(c, 40001, "参数错误"); return }; if err := h.svc.CreateAnnouncement(&a); err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, a) }
func (h *ActivityHandler) CreateActivity(c *gin.Context) { var a model.Activity; if err := c.ShouldBindJSON(&a); err != nil { response.Error(c, 40001, "参数错误"); return }; if a.Status == "" { a.Status = "published" }; if err := h.svc.CreateActivity(&a); err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, a) }
