package handler
import ("strconv"; "github.com/gin-gonic/gin"; "github.com/wtb-ordering/pkg/response"; "github.com/wtb-ordering/services/payment/service")
type PaymentHandler struct{ svc *service.PaymentService }
func NewPaymentHandler(svc *service.PaymentService) *PaymentHandler { return &PaymentHandler{svc: svc} }
func (h *PaymentHandler) Create(c *gin.Context) { var req struct{ OrderNo string `json:"order_no"`; Amount int `json:"amount"`; Channel string `json:"channel"` }; if err := c.ShouldBindJSON(&req); err != nil { response.Error(c, 40001, "参数错误"); return }; uid, _ := strconv.ParseUint(c.GetString("user_id"), 10, 64); po, err := h.svc.CreatePayment(req.OrderNo, uint(uid), req.Amount, req.Channel); if err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, po) }
func (h *PaymentHandler) WxPrepay(c *gin.Context) { response.Success(c, gin.H{"prepay_id": "mock_prepay_id"}) }
func (h *PaymentHandler) BalancePay(c *gin.Context) { var req struct{ OutTradeNo string `json:"out_trade_no"` }; if err := c.ShouldBindJSON(&req); err != nil { response.Error(c, 40001, "参数错误"); return }; if err := h.svc.BalancePay(req.OutTradeNo); err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, gin.H{"out_trade_no": req.OutTradeNo}) }
func (h *PaymentHandler) Recharge(c *gin.Context) { var req struct{ Amount int `json:"amount"` }; if err := c.ShouldBindJSON(&req); err != nil || req.Amount <= 0 { response.Error(c, 40001, "充值金额无效"); return }; uid, _ := strconv.ParseUint(c.GetString("user_id"), 10, 64); ro, err := h.svc.Recharge(uint(uid), req.Amount); if err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, ro) }
func (h *PaymentHandler) WxCallback(c *gin.Context) { var req struct{ OutTradeNo string `json:"out_trade_no"`; TransactionID string `json:"transaction_id"` }; if err := c.ShouldBindJSON(&req); err != nil { response.Error(c, 40001, "参数错误"); return }; if err := h.svc.WxCallback(req.OutTradeNo, req.TransactionID); err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, gin.H{"out_trade_no": req.OutTradeNo}) }
func (h *PaymentHandler) Refund(c *gin.Context) { var req struct{ OutTradeNo string `json:"out_trade_no"`; Amount int `json:"amount"`; Reason string `json:"reason"` }; if err := c.ShouldBindJSON(&req); err != nil { response.Error(c, 40001, "参数错误"); return }; if err := h.svc.Refund(req.OutTradeNo, req.Amount, req.Reason); err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, gin.H{"out_trade_no": req.OutTradeNo}) }
func (h *PaymentHandler) Query(c *gin.Context) { no := c.Param("outTradeNo"); po, err := h.svc.Query(no); if err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, po) }
