package handler
import ("strconv"; "github.com/gin-gonic/gin"; "github.com/wtb-ordering/pkg/response"; "github.com/wtb-ordering/services/points/model"; "github.com/wtb-ordering/services/points/service")
type PointsHandler struct{ svc *service.PointsService }
func NewPointsHandler(svc *service.PointsService) *PointsHandler { return &PointsHandler{svc: svc} }
func (h *PointsHandler) GetAccount(c *gin.Context) { uid, _ := strconv.ParseUint(c.GetString("user_id"), 10, 64); up, err := h.svc.GetAccount(uint(uid)); if err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, up) }
func (h *PointsHandler) GetLogs(c *gin.Context) { uid, _ := strconv.ParseUint(c.GetString("user_id"), 10, 64); page, _ := strconv.Atoi(c.DefaultQuery("page", "1")); pageSize, _ := strconv.Atoi(c.DefaultQuery("pageSize", "20")); list, total, err := h.svc.GetLogs(uint(uid), page, pageSize); if err != nil { response.Error(c, 50001, err.Error()); return }; response.SuccessPage(c, total, page, pageSize, list) }
func (h *PointsHandler) ListGoods(c *gin.Context) { list, err := h.svc.ListGoods(); if err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, list) }
func (h *PointsHandler) CreateGoods(c *gin.Context) { var g model.ExchangeGoods; if err := c.ShouldBindJSON(&g); err != nil { response.Error(c, 40001, "参数错误"); return }; if err := h.svc.CreateGoods(&g); err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, g) }
func (h *PointsHandler) Exchange(c *gin.Context) { var req struct{ GoodsID uint `json:"goods_id"` }; if err := c.ShouldBindJSON(&req); err != nil { response.Error(c, 40001, "参数错误"); return }; uid, _ := strconv.ParseUint(c.GetString("user_id"), 10, 64); order, err := h.svc.Exchange(uint(uid), req.GoodsID); if err != nil { if err.Error() == "积分不足" { response.Error(c, 40007, err.Error()); return }; response.Error(c, 50001, err.Error()); return }; response.Success(c, order) }
func (h *PointsHandler) GrantPoints(c *gin.Context) { var req struct{ UserID uint `json:"user_id"`; Amount int `json:"amount"`; SourceID string `json:"source_id"`; Remark string `json:"remark"` }; if err := c.ShouldBindJSON(&req); err != nil { response.Error(c, 40001, "参数错误"); return }; if err := h.svc.GrantPoints(req.UserID, req.Amount, req.SourceID, req.Remark); err != nil { response.Error(c, 50001, err.Error()); return }; response.Success(c, gin.H{"user_id": req.UserID, "granted": req.Amount}) }
